### ISSUE TITLE
small ptoblem here

### ISSUE THREAD

**Issue by russeldelossantos09** [Surender-K/RegistrationApp#1]
Can you give me the .sql database for this pls. Then im getting crashed when i login i uploaded the php files and created a database but im getting crashed everytime i click login or reset password and register. What is the problem in there?

**Comment by Surender-K** [comment]
Hello,
Database script is attached. 
Create a new database in mySQL. Extract the zip file and open it in any text editor. Copy all the lines of code. Open phpMyAdmin and run this query to create database tables.

[database.zip](https://github.com/Surender-K/RegistrationApp/files/1057803/database.zip)
